# Generated by Django 3.0.6 on 2020-06-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
