# Generated by Django 3.0.6 on 2020-06-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("posts", "0003_post_cover")]

    operations = [
        migrations.RenameField(model_name="post", old_name="cover", new_name="image")
    ]
